### ISSUE TITLE
DB should contain the number of commits per user per month for each repo

### ISSUE THREAD

**Issue by lourot** [ghuser-io/db#7]
So that the front end can show a timeline.

e.g. at https://github.com/ghuser-io/db/blob/a9c116e/data/repos/reframejs/reframe.json#L49

```
  "contributors": {
    "AurelienLourot": 11,
    "tdfranklin": 22,
    "brillout": 2038,
    "yuxal": 4
  },
```

should become something like

```
  "contributors_2": {
    "AurelienLourot": {
      "2018-01": 1,
      "2018-03": 5,
      "2018-04": 5,
    }
    "tdfranklin": {
      "2018-02": 1,
      "2018-04": 10,
      "2018-05": 11,
    },
    ...
  },
```

Note: it makes sense to work on this and #6 at the same time.

@brillout would you rather have the data per week instead? Weeks and months aren't aligned and I think you might have a harder time on the frontend if the data is per week.

**Comment by lourot** [comment]
@brillout the data is ready 🎉 e.g. https://s3.amazonaws.com/ghuser/data/repoCommits/reframejs/reframe.json

**Comment by brillout** [comment]
Neat 😍
